_target_: pytorch_lightning.Trainer

strategy: ddp
gpus: [0,1,2,3]

min_epochs: 1
max_epochs: 100

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1

# ckpt path
resume_from_checkpoint: null
