_target_: src.datamodules.fno_2d_datamodule.FNO2dDatamodule

dataset:
  _target_: src.datamodules.fno_2d_datamodule.FNO2dDataset
  data_dir: ${data_dir} # data_dir is specified in config.yaml
  
batch_size: 32
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
