_target_: src.datamodules.fno_2d_datamodule.FNO2dDataModule

dataset:
  _target_: src.datamodules.fno_2d_datamodule.FNO2dDataset
  data_path: "/disk/student/dvoytan/Desktop/Forward_Solver/work/work_fno_DL-BASED-model-building/solutions/*"
  n_models: 1400
  x_shape: [0, 301.01, 0.01]
  y_shape: [0, 201.01, 0.01]
  reshape_shape: [301, 201]
  stage: "train"
  y_rescale: 10000.0
  train_freqs: [0.5, 10.1, 0.5]  # Start stop step for arange
  test_freqs: [0.25, 10.25, 0.5]
  
batch_size: 32
train_val_test_split: [1200, 200, 200]
num_workers: 0
pin_memory: False
